//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Haley.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Haley.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HaleyActive {
            get {
                object obj = ResourceManager.GetObject("HaleyActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HaleyAwake {
            get {
                object obj = ResourceManager.GetObject("HaleyAwake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [haley,002]
        ///[wagwan,003]
        ///[hello,003]
        ///[bye haley,004]
        ///[good bye haley,004]
        ///[what is the time,005]
        ///[tell me the time,005]
        ///[whats the time,005]
        ///[what is the time right now,005]
        ///[what time is it,005]
        ///[what is the date,006]
        ///[whats the date,006]
        ///[what day is it today,006]
        ///[whats the date today,006]
        ///[select music,007]
        ///[i need music,007]
        ///[select song,007]
        ///[play music,009]
        ///[play the music,009]
        ///[play song,009]
        ///[play the song,009]
        ///[stop music,010]
        ///[stop the music,010]
        ///[stop the song,010]
        ///[stop the audio,010]
        ///[pause th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HaleyCommands {
            get {
                return ResourceManager.GetString("HaleyCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Sir this is haley, 1/Haley Lock and Load, 1/Haley is fully operational sir, 1/Yes Sir, 2/Here Sir, 2/Wagwan Sir, 3/Hello Sir, 3/What&apos;s up Sir, 3/Hi Sir, 3/Yes Sir, 3/Bye Bye Sir, 4/Seeya Sir, 4/Good Bye Sir, 4/The time is, 5/Right now it is, 5/Time right now is, 5/The date is, 6/The date today is, 6/Today is, 6/What song sir, 7/Which song sir, 7/Which song would you like, 7/Which song do you want sir, 7/Cancelling, 0/Ending Proccess, 8/Cancelled, 8/Ended, 8/OK, 8/.
        /// </summary>
        public static string HaleyResponce {
            get {
                return ResourceManager.GetString("HaleyResponce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HaleySleep {
            get {
                object obj = ResourceManager.GetObject("HaleySleep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
